name: frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    # uses-material-design: true

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  flutter_fluid_slider_nnbd: ^0.0.1+3
  percent_indicator: ^4.2.2
  flutter_svg: ^2.0.1
  audioplayers: ^3.0.1
  onboarding: ^3.1.0
  record: ^4.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_spinkit: ^5.1.0
  flutter_audio_waveforms: ^1.2.1+8
  audio_waveforms: ^1.0.3
  microphone: ^0.1.0
  flutter_sound: ^9.2.13
  syncfusion_flutter_gauges: ^20.4.53
  url_launcher: ^6.1.10
  audio_video_progress_bar: ^1.0.1
  shared_preferences: ^2.1.0
  helper: ^0.0.6
  file_picker: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  font_awesome_flutter: ^10.4.0
  flutter_switch: ^0.3.2
  provider: ^6.0.5
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  ionicons: ^0.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Splash images
    - assets/img/splash.png
    - assets/img/imgSpl.png

    # Onboarding images
    - assets/img/onboarding_1.png
    - assets/img/onboarding_2.png
    - assets/img/onboarding_3.png

    # Dashboard images
    - assets/img/dashboard_drawer.png

    # Card images
    - assets/img/record_card.png
    - assets/img/try_card.png

    # Ranking svgs
    - assets/svg/crown.svg
    - assets/svg/second.svg
    - assets/svg/third.svg

    # Helper svgs
    - assets/svg/arrow-right-alt.svg
    - assets/svg/speech.svg

    # Developer img
    - assets/img/ng.jpg
    - assets/img/kr.jpeg
    - assets/img/kd.jpg
    - assets/img/pg.png

    # Help image
    - assets/img/getting.jpg
    - assets/img/dashboard.jpg
    - assets/img/record.jpg
    - assets/img/prize.jpg
    - assets/img/permission.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

    - family: MarckScript
      fonts:
        - asset: assets/fonts/MarckScript-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
